@baseAddress = http://localhost:5090
@categoryId = 08ddee43-004a-66cf-107c-612569090000


GET {{baseAddress}}/api/categories
Accept: application/json
###

POST {{baseAddress}}/api/categories
Content-Type: application/json
Accept: application/json
{
  "name": "New Category"
}
###

GET {{baseAddress}}/api/categories/{{categoryId}}}
Accept: application/json
###


