@baseAddress = http://localhost:5090
@categoryId = 08ddee61-7663-69e9-107c-612569090000
@courseId = 08ddee61-768f-fd74-107c-612569090000
@userId = 69090000-6125-107c-c133-08ddee61768f

GET {{baseAddress}}/api/categories
Accept: application/json
###

POST {{baseAddress}}/api/categories
Content-Type: application/json
Accept: application/json
{
  "name": "New Category"
}
###

GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###

POST {{baseAddress}}/api/Courses
Content-Type: application/json
Accept: application/json
{
  "name": "New Course",
  "description": "This is a new course.",
  "categoryId": "{{categoryId}}",
  "imageUrl": "http://example.com/picture.jpg",
  "price": 49.99
}
###

PUT {{baseAddress}}/api/Courses
Content-Type: application/json
Accept: application/json
{
  "id": "{{courseId}}",
  "name": "Updated Course Name",
  "description": "This is an updated description.",
  "categoryId": "{{categoryId}}",
  "imageUrl": "http://example.com/updated-picture.jpg",
  "price": 59.99
}
###

GET {{baseAddress}}/api/Courses
Accept: application/json
###

GET {{baseAddress}}/api/Courses/{{courseId}}
Accept: application/json
###

DELETE {{baseAddress}}/api/Courses/{{courseId}}
Accept: application/json
###

GET {{baseAddress}}/api/Courses/user/{{userId}}
Accept: application/json
###

